---
#

- name: Configure splunk monitoring console to join index cluster
  shell: /opt/splunk/bin/splunk edit cluster-config -master_uri https://{{ master_internal_ip }}:{{ splunkd_port }} -mode {{ cluster_mode }} -site site{{site_count}} -secret {{ idxcluster_secret }} -auth {{ splkuser }}:{{ splkpass }}
  become: yes
  become_user: splunk
  ignore_errors: yes
  register: add_mc_to_idxcluster_result

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
#  async: 45
  when: add_sh_mc_idxcluster_result is succeeded 
